### ISSUE TITLE
runtime error: index out of range [#number] with length 128

### ISSUE THREAD

**Issue by MStoykov** [dlclark/regexp2#36]
This is again from fuzzing: 

```golang
package main

import (
        "fmt"
        "runtime/debug"

        "github.com/dlclark/regexp2"
)

var testCases = []struct {
        r, s []byte
}{
        {
                r: []byte{0x30, 0xbf, 0x30, 0x2a, 0x30, 0x30},
                s: []byte{0xf0, 0xb0, 0x80, 0x91, 0xf7},
        },
        {
                s: []byte{0xf3, 0x80, 0x80, 0x87, 0x80, 0x89},
                r: []byte{0x30, 0xaf, 0xf3, 0x30, 0x2a},
        },
}

func test(r, s []byte) (b bool) {
        defer func() {
                if r := recover(); r != nil {
                        fmt.Println(r)
                        debug.PrintStack()
                        b = true
                }
        }()

        re, err := regexp2.Compile(string(r), regexp2.ECMAScript)
        if err != nil {
                return false
        }
        _, _ = re.FindStringMatch(string(s))
        return false
}

func main() {
        for _, c := range testCases {
                fmt.Printf("Test case regex='%#v', string='%#v' panics\nstring values '%s', '%s'\n",
                        c.r, c.s, string(c.r), string(c.s),
                )
                fmt.Println("#############################################################################")
                if test(c.r, c.s) {
                } else {
                        fmt.Printf("Test case regex='%#v', string='%#v' DOES NOT panic\nstring values '%s', '%s'\n",
                                c.r, c.s, string(c.r), string(c.s),
                        )
                }
        }
}
```

will get you 
```
est case regex='[]byte{0x30, 0xbf, 0x30, 0x2a, 0x30, 0x30}', string='[]byte{0xf0, 0xb0, 0x80, 0x91, 0xf7}' panics
string values '00*00', '𰀑'
#############################################################################
runtime error: index out of range [196625] with length 128
goroutine 1 [running]:
runtime/debug.Stack(0x3b, 0x0, 0x0)
        /home/mstoykov/.gvm/gos/go1.14.9/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /home/mstoykov/.gvm/gos/go1.14.9/src/runtime/debug/stack.go:16 +0x22
main.test.func1(0xc000113e38)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/mstoykov/goja-regexp2-fuzzing/crashers/test.go:27 +0x97
panic(0x4f0ac0, 0xc0001420a0)
        /home/mstoykov/.gvm/gos/go1.14.9/src/runtime/panic.go:969 +0x166
github.com/dlclark/regexp2/syntax.(*BmPrefix).Scan(0xc0001602a0, 0xc000136078, 0x2, 0x2, 0x0, 0x0, 0x2, 0x7f9a4a2befb8)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/syntax/prefix.go:716 +0x3be
github.com/dlclark/regexp2.(*runner).findFirstChar(0xc000170000, 0xc000170000)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/runner.go:1305 +0x4d3
github.com/dlclark/regexp2.(*runner).scan(0xc000170000, 0xc000136078, 0x2, 0x2, 0x0, 0xc000113d00, 0x7fffffffffffffff, 0x4, 0xfffd, 0x5)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/runner.go:130 +0x128
github.com/dlclark/regexp2.(*Regexp).run(0xc00016e080, 0xc000113d00, 0xffffffffffffffff, 0xc000136078, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/runner.go:91 +0xf0
github.com/dlclark/regexp2.(*Regexp).FindStringMatch(...)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/regexp.go:159
main.test(0x5ba04c, 0x6, 0x6, 0x5ba034, 0x5, 0x5, 0x0)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/mstoykov/goja-regexp2-fuzzing/crashers/test.go:36 +0x168
main.main()
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/mstoykov/goja-regexp2-fuzzing/crashers/test.go:46 +0x355
Test case regex='[]byte{0x30, 0xaf, 0xf3, 0x30, 0x2a}', string='[]byte{0xf3, 0x80, 0x80, 0x87, 0x80, 0x89}' panics
string values '00*', '󀀇'
#############################################################################
runtime error: index out of range [786439] with length 128
goroutine 1 [running]:
runtime/debug.Stack(0x3b, 0x0, 0x0)
        /home/mstoykov/.gvm/gos/go1.14.9/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /home/mstoykov/.gvm/gos/go1.14.9/src/runtime/debug/stack.go:16 +0x22
main.test.func1(0xc000113e38)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/mstoykov/goja-regexp2-fuzzing/crashers/test.go:27 +0x97
panic(0x4f0ac0, 0xc000142100)
        /home/mstoykov/.gvm/gos/go1.14.9/src/runtime/panic.go:969 +0x166
github.com/dlclark/regexp2/syntax.(*BmPrefix).Scan(0xc000160540, 0xc0001360d0, 0x3, 0x4, 0x0, 0x0, 0x3, 0xc00016e100)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/syntax/prefix.go:716 +0x3be
github.com/dlclark/regexp2.(*runner).findFirstChar(0xc000170100, 0xc000170100)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/runner.go:1305 +0x4d3
github.com/dlclark/regexp2.(*runner).scan(0xc000170100, 0xc0001360d0, 0x3, 0x4, 0x0, 0xc000113d00, 0x7fffffffffffffff, 0x5, 0xfffd, 0x6)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/runner.go:130 +0x128
github.com/dlclark/regexp2.(*Regexp).run(0xc00016e180, 0xc000113d00, 0xffffffffffffffff, 0xc0001360d0, 0x3, 0x4, 0x0, 0x0, 0x0)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/runner.go:91 +0xf0
github.com/dlclark/regexp2.(*Regexp).FindStringMatch(...)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/dlclark/regexp2/regexp.go:159
main.test(0x5ba03c, 0x5, 0x5, 0x5ba054, 0x6, 0x6, 0x0)
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/mstoykov/goja-regexp2-fuzzing/crashers/test.go:36 +0x168
main.main()
        /home/mstoykov/.gvm/pkgsets/go1.14.9/global/src/github.com/mstoykov/goja-regexp2-fuzzing/crashers/test.go:46 +0x355
```

I have more test cases but these ones were the shortest and just as readable :(

**Comment by dlclark** [comment]
Ok, this was caused by a bug in the port -- .NET runes are 16-bit and Go runes are 32-bit, so a bit mask in the prefix was incorrect (assumed 16-bit numbers).
